#
###################################
# Site wide configuration
####################################
#
title: Farrago of Concepts in Machine Learning
email: anandkrish894@gmail.com
description: Companion Website for FCML book
url: https://antixk.github.io/fcmlbook/ # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Tokyo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Farrago of Concepts in Machine Learning
  avatar: book_logo.png
  job: "A comphrehensive look at Machine Learning"
  bio: "&#169; 2018 by Anand Krishnamoorthy"
  email: anandkrish894@gmail.com
  disqus-shortname: antixk
  twitter: AnandkrishAK #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: AntixK #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: anandkrishak #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
